[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "STEGO.R"
authors = [{name = "Kerry Mullan", email = "kerry.mullan@uantwerpen.be"}]
dynamic = ["version", "description"]
